export const drugs = [
  "Paracetamol",
  "Panadol",
  "Pantoprazole",
  "Phenobarbital",
  "Pioglitazone",
  "Prednisolone",
  "Propranolol",
  "Paroxetine",
  "Pyrantel Pamoate",
  "Aspirin",
  "Ibuprofen",
  "Amoxicillin",
  "Ciprofloxacin",
  "Lisinopril",
  "Metformin",
  "Atorvastatin",
  "Omeprazole",
  "Hydrochlorothiazide",
  "Metoprolol",
];
